export const metadata = {
  title: "Login - Notion Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="h-full bg-red-500">
        {children}
    </div>
  );
}
